// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';

export function DeleteConnection(arg1:string):Promise<void>;

export function LoadConnections():Promise<Array<connections.Connection>>;

export function SaveConnection(arg1:connections.Connection):Promise<void>;
