// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseConnection(arg1) {
  return window['go']['connectionsBinding']['ConnectionsBinding']['CloseConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['connectionsBinding']['ConnectionsBinding']['DeleteConnection'](arg1);
}

export function GetPasswordBehaviours() {
  return window['go']['connectionsBinding']['ConnectionsBinding']['GetPasswordBehaviours']();
}

export function GetTableData(arg1, arg2) {
  return window['go']['connectionsBinding']['ConnectionsBinding']['GetTableData'](arg1, arg2);
}

export function GetTables(arg1, arg2) {
  return window['go']['connectionsBinding']['ConnectionsBinding']['GetTables'](arg1, arg2);
}

export function LoadConnections() {
  return window['go']['connectionsBinding']['ConnectionsBinding']['LoadConnections']();
}

export function OpenConnection(arg1) {
  return window['go']['connectionsBinding']['ConnectionsBinding']['OpenConnection'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['connectionsBinding']['ConnectionsBinding']['SaveConnection'](arg1);
}
