// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['connectionsbinding']['ConnectionsBinding']['DeleteConnection'](arg1);
}

export function LoadConnections() {
  return window['go']['connectionsbinding']['ConnectionsBinding']['LoadConnections']();
}

export function SaveConnection(arg1) {
  return window['go']['connectionsbinding']['ConnectionsBinding']['SaveConnection'](arg1);
}
