// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';
import {connectionsBinding} from '../models';

export function CloseConnection(arg1:connections.Connection):Promise<void>;

export function DeleteConnection(arg1:connections.Connection):Promise<void>;

export function GetPasswordBehaviours():Promise<Array<connections.PasswordBehaviourDescription>>;

export function GetTableData(arg1:connections.Connection,arg2:string):Promise<Array<connectionsBinding.DatabaseColumn>>;

export function GetTables(arg1:connections.Connection,arg2:string):Promise<Array<string>>;

export function LoadConnections():Promise<Array<connections.Connection>>;

export function OpenConnection(arg1:connections.Connection):Promise<void>;

export function SaveConnection(arg1:connections.Connection):Promise<void>;
