// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';
import {queryBinding} from '../models';

export function GetTableData(arg1:connections.Connection,arg2:string):Promise<Array<queryBinding.DatabaseColumn>>;

export function GetTables(arg1:connections.Connection,arg2:string):Promise<Array<string>>;
