// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';
import {queryBindingTypes} from '../models';

export function GetTableData(arg1:connections.Connection,arg2:string):Promise<Array<queryBindingTypes.DatabaseColumn>>;

export function GetTables(arg1:connections.Connection,arg2:string,arg3:number):Promise<queryBindingTypes.GetTablesResult>;

export function LoadTableData(arg1:connections.Connection,arg2:string,arg3:number):Promise<queryBindingTypes.QueryResultTableData>;
