// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTableData(arg1, arg2) {
  return window['go']['queryBinding']['QueryBinding']['GetTableData'](arg1, arg2);
}

export function GetTables(arg1, arg2, arg3) {
  return window['go']['queryBinding']['QueryBinding']['GetTables'](arg1, arg2, arg3);
}

export function LoadTableData(arg1, arg2, arg3) {
  return window['go']['queryBinding']['QueryBinding']['LoadTableData'](arg1, arg2, arg3);
}
